# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SegmentPOC_mmt' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SegmentPOC_mmt

pod 'Analytics'
  
  target 'SegmentPOC_mmtTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
